---
title: "Sample Analysis"
author: "jschoenbachler & eoutland"
date: "2020-12-22"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

```{r}
library(data.table)
library(ggplot2)
library(tm)
library(ggwordcloud)
source('code/get_lyric_word_count.R')

```

## Importing Data, preprocessing

```{r}

songData = fread('data/song_data.csv.gz')
lyricData = getLyricWordCount(songData)

lyricData = merge(songData[, .(track_id, mode)]
                  , lyricData)
lyricData = lyricData[, .(count = sum(count)), by = .(mode, word)]
setorder(lyricData, mode, -count)

lyricData = lyricData[!(word %in% stopwords())]

```

## Analysis

```{r, echo=F}

majorLyrics = lyricData[
  mode == 1][1:100]
minorLyrics = lyricData[
  mode == 0][1:100]

majorLyrics[!(word %in% minorLyrics[, word])]
minorLyrics[!(word %in% majorLyrics[, word])]

top100 = rbind(majorLyrics, minorLyrics)
top100[mode == 0, disjoint := ifelse(word %in% majorLyrics[, word], 1, 0)]
top100[mode == 1, disjoint := ifelse(word %in% minorLyrics[, word], 1, 0)]

modeLabels = c('Minor', 'Major')
names(modeLabels) = c(0, 1)

ggplot(data = top100) +
  
  geom_text_wordcloud(aes(label = word, size = count
                          , color = as.factor(disjoint))) +
  
  facet_wrap(~ mode, labeller = as_labeller(modeLabels)) +
  
  scale_size_area(max_size = 12) +
  
  theme_bw()

```
