---
title: "Josh Analysis"
author: "jschoenbachler"
date: "2020-12-22"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

## Introduction

I wanted to expand on my word danceability example from the sample analysis.


## Danceabile words relative to rest of song



```{r load libraries}
library(data.table)
library(ggplot2)
```


```{r load all data}
songDT = fread('data/song_data.csv.gz')
songDT[which(songDT$track_id == '7inXu0Eaeg02VsM8kHNvzM'),]$lyrics = as.character(NA)
head(songDT, 5)
```

```{r use word count}
source('code/get_lyric_word_count.R')
wordExclude = c('i', 'the', 'you', 'it', 'a', 'to', 'in', 'and', 'this', 'im', 'that', 'was', 'on', 'he')
lyricDT = getLyricWordCount(songDT, wordExclude = wordExclude)
head(lyricDT, 15)
head(getLyricWordCount(songDT, c('merry', 'holidays')), 15)
```

```{r analyze most danceable words relative to word total}
# Most Danceable Words
songDT = merge(songDT, lyricDT, by = c('track_id', 'track_name'))
songDT = songDT[, word_danceability_relative := ((count / word_total) * danceability)]
setorder(songDT, -word_danceability_relative)
cols = c('track_name', 'danceability', 'word_total', 'word', 'count', 'word_danceability_relative')
head(songDT[, ..cols], 20)
```

```{r analyze least danceable words relative to word total}
# Least Danceable Words
setorder(songDT, word_danceability_relative)
cols = c('track_name', 'danceability', 'word_total', 'word', 'count', 'word_danceability_relative')
head(songDT[, ..cols], 20)
```

```{r analyze most danceable words without word total relativity}
songDT = songDT[, word_danceability := (count * danceability)]
setorder(songDT, -word_danceability)
cols = c('track_name', 'danceability', 'word_total', 'word', 'count', 'word_danceability')
head(songDT[, ..cols], 20)
```

```{r analyze least danceable words without word total relativity}
# Least Danceable Words
setorder(songDT, word_danceability)
cols = c('track_name', 'danceability', 'word_total', 'word', 'count', 'word_danceability')
head(songDT[, ..cols], 20)
```
